complete implementation of home page product listing
profgrace/FashionBook pull request #2
Opened 2019-07-09 09:40 UTC by phemidawhiz

2019-07-10 06:39 UTC, profgrace requested changes

2019-07-10 06:39 UTC, profgrace commented on src/components/LatestCollections.vue
>        products: [
This has become redundant - get rid of it.

2019-07-10 08:13 UTC, phemidawhiz commented on src/components/LatestCollections.vue
>        products: [
Yeah... will do

2019-07-14 17:24 UTC, profgrace approved these changes

2019-07-19 09:51 UTC, merged